import 'dart:convert';
// class Autogenerated {
//   String result;
//   int count;
//   List<Payments> payments;

//   Autogenerated({this.result, this.count, this.payments});

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     result = json['result'];
//     count = json['count'];
//     if (json['payments'] != null) {
//       payments = new List<Payments>();
//       json['payments'].forEach((v) {
//         payments.add(new Payments.fromJson(v));
//       });
//     }
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['result'] = this.result;
//     data['count'] = this.count;
//     if (this.payments != null) {
//       data['payments'] = this.payments.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }

// class Payments {
//   String amount;
//   String destination;
//   String executedTime;
//   String source;

//   Payments({this.amount, this.destination, this.executedTime, this.source});

//   Payments.fromJson(Map<String, dynamic> json) {
//     amount = json['amount'];
//     destination = json['destination'];
//     executedTime = json['executed_time'];
//     source = json['source'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['amount'] = this.amount;
//     data['destination'] = this.destination;
//     data['executed_time'] = this.executedTime;
//     data['source'] = this.source;
//     return data;
//   }
// }



class Payments {
  String result;
  int count;
  List<Payment> payments;

  Payments.fromJson(String jsonStr) {
    final _map = jsonDecode(jsonStr);
    this.result = _map['result'];
    this.count = _map['count'];
    this.payments = [];
    final _paymentList = _map['payments'];

    for (var i = 0; i < (this.count); i++) {
      this.payments.add(new Payment.fromJson(_paymentList[i]));
    }
  }
}

class Payment {
  double amount;
  String source, destination;
  DateTime executedTime;

  Payment.fromJson(Map<String, dynamic> jsonMap) {
    this.amount = double.parse(jsonMap['amount']);
    this.source = jsonMap['source'];
    this.destination = jsonMap['destination'];
    this.executedTime = DateTime.parse(jsonMap['executed_time']);
  }
}